// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeF6OghFFqPlGS0CXb_9XZfgkFFucx0uw',
    appId: '1:382464457642:web:cb711f0aa01e7d71ac49d3',
    messagingSenderId: '382464457642',
    projectId: 'condition-report-go-92d23',
    authDomain: 'condition-report-go-92d23.firebaseapp.com',
    storageBucket: 'condition-report-go-92d23.appspot.com',
    measurementId: 'G-GLWJ51RS3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsnpeT8zJCo3QuQge92G-bIiRYiZ4LRc',
    appId: '1:382464457642:android:f9bc32cfce1aa6caac49d3',
    messagingSenderId: '382464457642',
    projectId: 'condition-report-go-92d23',
    storageBucket: 'condition-report-go-92d23.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeF6OghFFqPlGS0CXb_9XZfgkFFucx0uw',
    appId: '1:382464457642:web:71a9caf6b653049aac49d3',
    messagingSenderId: '382464457642',
    projectId: 'condition-report-go-92d23',
    authDomain: 'condition-report-go-92d23.firebaseapp.com',
    storageBucket: 'condition-report-go-92d23.appspot.com',
    measurementId: 'G-L5STZC2CQE',
  );
}
